[target.i686-unknown-linux-gnu]
image = "ghcr.io/cross-rs/i686-unknown-linux-gnu:main"

[target.i686-unknown-linux-gnu.env]
OPENSSL_STATIC = "1"
PKG_CONFIG_ALLOW_CROSS = "1"
RUSTFLAGS = "-C target-feature=+crt-static"
OPENSSL_DIR = "/usr"
CARGO_FEATURE_VENDORED = "1"
CARGO_FEATURE_VENDORED_OPENSSL = "1"

[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main"

[target.aarch64-unknown-linux-gnu.env]
OPENSSL_STATIC = "1"
PKG_CONFIG_ALLOW_CROSS = "1"
RUSTFLAGS = "-C target-feature=+crt-static"
OPENSSL_DIR = "/usr"
CARGO_FEATURE_VENDORED = "1"
CARGO_FEATURE_VENDORED_OPENSSL = "1"

[target.x86_64-unknown-linux-musl]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-musl:main"

[target.x86_64-unknown-linux-musl.env]
OPENSSL_STATIC = "1"
RUSTFLAGS = "-C target-feature=+crt-static"
OPENSSL_DIR = "/usr"
CARGO_FEATURE_VENDORED = "1"
CARGO_FEATURE_VENDORED_OPENSSL = "1"