[build]
xargo = false
default-target = "aarch64-unknown-linux-gnu"

[build.env]
passthrough = [
    "OPENSSL_STATIC",
    "PKG_CONFIG_ALLOW_CROSS",
    "OPENSSL_DIR",
    "CARGO_FEATURE_VENDORED",
    "CARGO_FEATURE_VENDORED_OPENSSL",
    "RUSTFLAGS"
]

[target.i686-unknown-linux-gnu]
image = "ghcr.io/cross-rs/i686-unknown-linux-gnu:main"

[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main"

[target.x86_64-unknown-linux-musl]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-musl:main"