name: Test Build

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # Simulated release job without actually creating a GitHub release
  test-version:
    name: test-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Using a fixed version for testing instead of extracting from tag
      - name: Set test version
        run: echo "VERSION=test-build" >> $GITHUB_ENV
      
      - name: Show the version
        run: |
          echo "version is: $VERSION"
    outputs:
      version: ${{ env.VERSION }}

  build-test:
    name: build-test
    needs: ['test-version']
    runs-on: ${{ matrix.os }}
    env:
      CARGO: cargo
      TARGET_FLAGS: 
      TARGET_DIR: ./target
      RUST_BACKTRACE: 1
      # Force static OpenSSL linking for all builds
      OPENSSL_STATIC: 1
      CARGO_FEATURE_VENDORED: 1
      PKG_CONFIG_ALLOW_CROSS: 1
    strategy:
      fail-fast: false
      matrix:
        include:
        - build: linux
          os: ubuntu-latest
          rust: stable
          target: x86_64-unknown-linux-musl
        - build: linux-x86
          os: ubuntu-latest
          rust: stable
          target: i686-unknown-linux-gnu
        - build: linux-aarch64
          os: ubuntu-latest
          rust: stable
          target: aarch64-unknown-linux-gnu
        - build: macos
          os: macos-latest
          rust: stable
          target: x86_64-apple-darwin
        - build: macos-aarch64
          os: macos-latest
          rust: stable
          target: aarch64-apple-darwin
        - build: win-msvc
          os: windows-latest
          rust: stable
          target: x86_64-pc-windows-msvc
        - build: win-gnu
          os: windows-latest
          rust: stable-x86_64-gnu
          target: x86_64-pc-windows-gnu
        - build: win32-msvc
          os: windows-latest
          rust: stable
          target: i686-pc-windows-msvc

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        target: ${{ matrix.target }}

    - name: Setup cross-compilation for Linux targets
      if: matrix.os == 'ubuntu-latest'
      run: |
        # Install needed cross-compilation tools
        sudo apt-get update
        sudo apt-get install -y pkg-config musl-tools
        
        # Install specific dependencies for different targets
        if [[ "${{ matrix.target }}" == "i686-unknown-linux-gnu" ]]; then
          sudo apt-get install -y gcc-multilib
        elif [[ "${{ matrix.target }}" == "aarch64-unknown-linux-gnu" ]]; then
          sudo apt-get install -y gcc-aarch64-linux-gnu
        fi
        
        # For non-musl targets, use cross
        if [[ "${{ matrix.target }}" != "x86_64-unknown-linux-musl" ]]; then
          cargo install cross --locked

          # Configuration for OpenSSL with cross
          echo "CARGO=cross" >> $GITHUB_ENV
          echo "OPENSSL_STATIC=1" >> $GITHUB_ENV
          echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV
          
          # Verify that Cross.toml exists and show its content
          if [[ -f "Cross.toml" ]]; then
            echo "Using existing Cross.toml file:"
            cat Cross.toml
          else
            echo "Warning: Cross.toml file not found in the repository."
          fi
        fi

    - name: Set target flags
      if: matrix.target != ''
      shell: bash
      run: |
        echo "TARGET_FLAGS=--target ${{ matrix.target }}" >> $GITHUB_ENV
        echo "TARGET_DIR=./target/${{ matrix.target }}" >> $GITHUB_ENV

    - name: Show build configuration
      shell: bash
      run: |
        echo "cargo command: ${{ env.CARGO }}"
        echo "target flags: ${{ env.TARGET_FLAGS }}"
        echo "target dir: ${{ env.TARGET_DIR }}"
        echo "openssl static: ${{ env.OPENSSL_STATIC }}"
        if [[ -f "Cross.toml" ]]; then
          echo "Cross.toml:"
          cat Cross.toml
        fi

    - name: Build release binary
      shell: bash
      run: |
        ${{ env.CARGO }} build --release ${{ env.TARGET_FLAGS }} --features vendored

    - name: Determine binary path and archive name
      shell: bash
      run: |
        version="${{ needs.test-version.outputs.version }}"
        
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          bin="target/${{ matrix.target }}/release/asp-classic-parser.exe"
          echo "ARCHIVE=asp-classic-parser-$version-${{ matrix.target }}.zip" >> $GITHUB_ENV
        else
          bin="target/${{ matrix.target }}/release/asp-classic-parser"
          echo "ARCHIVE=asp-classic-parser-$version-${{ matrix.target }}.tar.gz" >> $GITHUB_ENV
        fi
        
        echo "BIN=$bin" >> $GITHUB_ENV

    - name: Strip release binary (macOS)
      if: matrix.os == 'macos-latest'
      shell: bash
      run: strip "$BIN"

    - name: Strip release binary (Linux)
      if: matrix.os == 'ubuntu-latest' && env.CARGO != 'cross'
      shell: bash
      run: strip "$BIN"

    - name: Create archive directory
      shell: bash
      run: |
        mkdir -p dist
        cp "$BIN" dist/
        cp {README.md,CHANGELOG.md,LICENSE} dist/ || true

    - name: Create zip archive (Windows)
      if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        cd dist
        7z a "../$ARCHIVE" *
        cd ..
        certutil -hashfile "$ARCHIVE" SHA256 > "$ARCHIVE.sha256"

    - name: Create tar archive (Unix)
      if: matrix.os != 'windows-latest'
      shell: bash
      run: |
        tar -czf "$ARCHIVE" -C dist .
        shasum -a 256 "$ARCHIVE" > "$ARCHIVE.sha256"

    # Upload the artifacts to the workflow run
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.target }}
        path: |
          ${{ env.ARCHIVE }}
          ${{ env.ARCHIVE }}.sha256